Make METdatadb the primary loading method #350

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -19,6 +19,7 @@ ENV TOMCAT_VERSION ${TOMCAT_MAJOR_VERSION}.${TOMCAT_MINOR_VERSION}
 ENV METVIEWER_GIT_URL  https://github.com/dtcenter/METviewer
 ENV METCALCPY_GIT_URL  https://github.com/dtcenter/METcalcpy
 ENV METPLOTPY_GIT_URL  https://github.com/dtcenter/METplotpy
+ENV METDATADB_GIT_URL  https://github.com/dtcenter/METdatadb
 
 #
 # METVIEWER_GIT_NAME is required.
@@ -48,6 +49,16 @@ RUN if [ "x${METPLOTPY_GIT_NAME}" = "x" ]; then \
       exit 1; \
     else \
       echo "Build Argument METPLOTPY_GIT_NAME=${METPLOTPY_GIT_NAME}"; \
+    fi
+
+#
+# METDATADB_GIT_NAME is required.
+#
+RUN if [ "x${METDATADB_GIT_NAME}" = "x" ]; then \
+      echo "ERROR: METDATADB_GIT_NAME undefined! Rebuild with \"--build-arg METDATADB_GIT_NAME={branch, tag, or hash}\""; \
+      exit 1; \
+    else \
+      echo "Build Argument METDATADB_GIT_NAME=${METDATADB_GIT_NAME}"; \
     fi
 
 #
@@ -114,7 +125,11 @@ RUN mkdir /METviewer-python \
  && echo "Checking out METplotpy ${METPLOTPY_GIT_NAME} from ${METPLOTPY_GIT_URL}" \
  && git clone ${METPLOTPY_GIT_URL} /METviewer-python/METplotpy \
  && cd /METviewer-python/METplotpy \
- && git checkout ${METPLOTPY_NAME_TAG}
+ && git checkout ${METPLOTPY_NAME_TAG} \
+ && echo "Checking out METdatadb ${METDATADB_GIT_NAME} from ${METDATADB_GIT_URL}" \
+ && git clone ${METDATADB_GIT_URL} /METviewer-python/METdatadb \
+ && cd /METviewer-python/METdatadb \
+ && git checkout ${METDATADB_NAME_TAG}
 
 #
 # Install METviewer
@@ -124,7 +139,7 @@ RUN echo "Checking out METviewer ${METVIEWER_GIT_NAME} from ${METVIEWER_GIT_URL}
  && cd /METviewer \
  && git checkout ${METVIEWER_GIT_NAME} \
  && echo "Configuring and building METviewer" \
- && cd /METviewer \ 
+ && cd /METviewer \
  && cat webapp/metviewer/WEB-INF/classes/build.properties | \
     sed -r 's%db.host=.*%db.host=mysql_mv%g' | \
     sed -r 's%db.user=.*%db.user=root%g' | \
@@ -153,10 +168,8 @@ RUN echo "Checking out METviewer ${METVIEWER_GIT_NAME} from ${METVIEWER_GIT_URL}
     >  mv_batch.sh-DOCKER \
  && mv mv_batch.sh-DOCKER mv_batch.sh \
  && cat mv_load.sh | \
-    sed -r 's%JAVA=.*%JAVA=java\nMV_HOME=/METviewer%g' | \
-    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
-    sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/metplotpy/%g' \
+    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local/%g'  | \
+    sed -r 's%METDATADB_HOME=.*%METDATADB_HOME=/METviewer-python/METdatadb/%g' \
     >  mv_load.sh-DOCKER \
  && mv mv_load.sh-DOCKER mv_load.sh \
  && cat mv_scorecard.sh | \
